### PR TITLE
Update added Fedora OS

### PR DESCRIPTION
**Pull request by forkeer**
Fix Fedora OS error

### CODE REVIEW

**Comment by forkeer** [comment]
Please approved for fedora os support

**Comment by MHSanaei** [comment]
[done ](https://github.com/MHSanaei/3x-ui/commit/6337efb786ae1ff07c1c059882672b8af1b22fba)

**Comment by forkeer** [comment]
Not Solved , you manually edit and now 
Show again : 
 Please use Fedora 29 or higher

Thanks

**Comment by forkeer** [comment]
@MHSanaei

**Comment by forkeer** [comment]
@MHSanaei 

[root@linux ~]# cat /etc/fedora-release
Fedora release 37 (Thirty Seven)
[root@linux ~]# cat /proc/version
Linux version 6.1.14-200.fc37.x86_64 (mockbuild@bkernel01.iad2.fedoraproject.org) (gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4), GNU ld version 2.38-25.fc37) #1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:13:26 UTC 2023

**Pull request closed without merging**
