### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by tysonite**
The "x-ui settings" command does not exist. Only "x-ui setting" is there.

### CODE REVIEW

**Comment by MHSanaei** [comment]
We have x-ui settings

**Comment by tysonite** [comment]
```
yourhostname:/app# ./x-ui -v
(0x2a37d20,0xc000417a70)
2.4.11
yourhostname:/app# ./x-ui -h
(0x2a37d20,0xc00004b830)
Usage of ./x-ui:
  -v    show version

Commands:
    run            run web panel
    migrate        migrate form other/old x-ui
    **setting**        set settings
```

Am I doing smth wrong?

**Comment by tysonite** [comment]
https://github.com/MHSanaei/3x-ui/blob/4ad5a5aba4ec78dde614d8714555e10e6d1778cc/main.go#L447

Here too. *setting*, not *settings* when speaking about terminal.
As you wish of course, but this is confusing.

**Comment by MHSanaei** [comment]
It doesn't work on Docker; it's for the bash menu.
https://github.com/MHSanaei/3x-ui/blob/main/x-ui.sh#L1844

**Comment by tysonite** [comment]
Ohh. I see now. I'll probably come up with a different patch for README file expalaining this if you dont mind as newcomers like me may likely miss this difference.

**Pull request closed without merging**
