### PR TITLE
support for openEuler

### PR DESCRIPTION
**Pull request by bnam999**

### CODE REVIEW

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/pull/2573#issuecomment-2395450077

**Comment by bnam999** [comment]
Because CentOS stop updating.  openEuler is a substitution of it.  Almost same as CentOS 8.  I had installed successfully on it.

**Comment by MHSanaei** [comment]
Please update the readme for all languages.

**Comment by MHSanaei** [comment]
And please put it before CentOS because it doesn't have a version check.

**Comment by bnam999** [comment]
[root@linux21 ~]# cat /etc/os-release 
NAME="openEuler"
VERSION="24.03 (LTS)"
ID="openEuler"
VERSION_ID="24.03"
PRETTY_NAME="openEuler 24.03 (LTS)"
ANSI_COLOR="0;31"

**Comment by MHSanaei** [comment]
If you want to add a version for it, use this:
2303

**Comment by bnam999** [comment]
Do not know how to add 2203. you can add it by yourself. I will learn it.

**Comment by MHSanaei** [comment]
elif [[ "${release}" == "openEuler" ]]; then
if [[ ${os_version} -lt 2203 ]]; then 
          echo -e "${red} Please use openEuler 22.03 or higher ${plain}\n" && exit 1 
      fi

**Comment by bnam999** [comment]
ok. I will add it now.

**Comment by bnam999** [comment]
added

**Pull request merged**
