### PR TITLE
Some new buttons for bot and ability to use userId in tgId

### PR DESCRIPTION
**Pull request by masoud-hidden**
Added buttons:
IP Log
IP Limit
Enable/Disable

Ability to use the telegram User ID in the Telegram Username field.

### CODE REVIEW

**Comment by MHSanaei** [comment]
nice thank you for your great work, I just checked everything works fine except "Ability to use a telegram User ID in Telegram Username"
if I'm not wrong you mean we can set a user id for the client?
I test that but doesn't work

**Comment by masoud-hidden** [comment]
> nice thank you for your great work, I just checked everything works fine except "Ability to use a telegram User ID in Telegram Username" if I'm not wrong you mean we can set a user id for the client? I test that but doesn't work

Yes, You can set a user id for the client. Add a number sign (#) before the user id and set it to the Telegram Username field in the client settings. Test it with a normal telegram user not an admin user.
Like this:
User ID = 987654321
Telegram Username (in the client settings) = #987654321

**Comment by MHSanaei** [comment]
i test it again but as you can see but still doesn't work like when we use username
Screenshot 2023-05-06 014818

**Comment by masoud-hidden** [comment]
> i test it again but as you can see but still doesn't work like when we use username Screenshot 2023-05-06 014818

Can I see what you received from the bot when the user id is set?

**Comment by MHSanaei** [comment]
Your configuration is not found!
Please ask your Admin to use your telegram username in your configuration(s).

Your username: @MHSanaei1

**Comment by masoud-hidden** [comment]
I will fix it soon.

**Comment by masoud-hidden** [comment]
I can remove the (#) in the next commit, Is it good?

**Comment by MHSanaei** [comment]
yes it will be even better thanks for that

**Comment by masoud-hidden** [comment]
Don't forget to remove the # from the client settings.

**Comment by MHSanaei** [comment]
well done

**Pull request merged**
