### PR TITLE
fixed some grammar errors

### PR DESCRIPTION
**Pull request by OohWhatever**
Fixed some errors with words that starts with lowercase like:
image

### CODE REVIEW

**Comment by OohWhatever** [comment]
also there is no word like "Балансиры" in RU, changed it to right version

**Comment by MHSanaei** [comment]
thanks

**Comment by 3ayazaya** [comment]
Cool. Big impact bro! Balancers so good!

**Comment by copyb4r2** [comment]
Wow, bro. You work is so impactful!

**Pull request merged**
