### PR TITLE
[Feature] import/export database in the panel

### PR DESCRIPTION
**Pull request by hamid-gh98**
- added feature to import/export database in the panel in backup modal
- added api route to upload db 'server/importDB'
- updated translation

### CODE REVIEW

**Comment by MHSanaei** [comment]
thanks again can you just remove the last part about migration I revert Cobra PR it was a mistake to accept that

**Comment by hamid-gh98** [comment]
No problem, Done!

**Comment by MHSanaei** [comment]
I just test it now but when I try to upload my database I got this error 
"Fail: Error backup temporary db file: rename /etc/x-ui/x-ui.db /etc/x-ui/x-ui.db.backup: The process cannot access the file because it is being used by another process."

**Comment by MHSanaei** [comment]
update2: I just checked my database import to inbound 
but still, I got that error 
and xray needs to be restarted please add auto restart for that 
thank you so much

**Comment by hamid-gh98** [comment]
> update2: I just checked my database import to inbound but still, I got that error and xray needs to be restarted please add auto restart for that thank you so much

I have tested it and it is working for me. Could you please check if it is being used by another process, such as a database manager?
Additionally, Xray will automatically restart once the import is complete.

**Comment by hamid-gh98** [comment]
I've made some changes. Would you mind testing it now?

**Comment by MHSanaei** [comment]
xray config problem is solved thanks for that, but if you check the database file it's empty it just made a temp file everything is on that because can't replace it when it's used by the panel 

Screenshot 2023-05-06 012804

**Comment by hamid-gh98** [comment]
> but if you check the database file it's empty it just made a temp file everything is on that because can't replace it when it's used by the panel

I have tried several times and everything appears to be working fine. and could you please check it now?
Did it throw any errors during this process?

The function stops the Xray, moves the database from the temp file to the db location, and then restarts Xray.

It's possible that another program is currently using it. can you try the following ?
- Close other programs or processes that may be using it.
- Check if there are any permission issues that might be preventing access.

**Pull request merged**
