### PR TITLE
docker: refactor

### PR DESCRIPTION
**Pull request by s0me1newithhand7s**
- [x] Yes i've tested locally

## Why
1. Edited shebangs to be *right*, as [calling binaries trough `env` is right way](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash).
2. Switched to `golang:bookworm` in builder and `ubuntu:latest` in 3x-ui itself. It isn't so important for builder, but for `x-ui.sh` itself - it is.

### CODE REVIEW

**Comment by s0me1newithhand7s** [comment]
i can rebase if needed

**Comment by aski425** [comment]
please, it to "bookworm", because after I accidentally drop it, it is not convenient to restore it, because you have to do everything from the beginning, I would like it to be possible through cli and with docker can be done.

**Comment by s0me1newithhand7s** [comment]
and **pls** don't silently close this PR
i am open to cooperate

**Comment by KiGamji** [comment]
why would you switch from a smaller, lighter distro, to debian and ubuntu

**Comment by s0me1newithhand7s** [comment]
> why would you switch from a smaller, lighter distro, to debian and ubuntu

"Switched to golang:bookworm in builder and ubuntu:latest in 3x-ui itself. It isn't so important for builder, but for x-ui.sh itself - it is."

**Comment by alireza0** [comment]
IMHO:
1. Using `x-ui.sh` in docker is not recommended
2. Using unstable debian version `bookworm` is not recommended
3. Using very large `ubuntu` image has not any good point

Instead you can use one of these solutions:
1. Only use `noble` for all stages.
2. Use separate `alpine` image without any `x-ui.sh` script beside another image `noble` ( in both builder and 3x-ui ) with `x-ui.sh` script. Then you could have two images: `3x-ui:alpine` and `3x-ui:noble`

**Comment by s0me1newithhand7s** [comment]
> Using `x-ui.sh` in docker is not recommended
fully agreed but why not fixing it bc we actually can?

> Only use `noble` for all stages.
OK, i'll do it ASAP

> Use separate `alpine` image without any `x-ui.sh` script beside another image `noble` ( in both builder and 3x-ui ) with `x-ui.sh` script. Then you could have two images: `3x-ui:alpine` and `3x-ui:noble`
sound a bit over-complicated as my goal was to *just fix*, but i'll do my best

**Comment by s0me1newithhand7s** [comment]
let's cooperate then

**Comment by KiGamji** [comment]
> 2\. Using unstable debian version `bookworm` is not recommended

huh? bookworm was released on 10 June 2023

**Comment by s0me1newithhand7s** [comment]
> > 2. Using unstable debian version `bookworm` is not recommended
> 
> huh? bookworm was released on 10 June 2023

nwm i've switched to `golang:alpine` since building platform have no impact, at all

**Comment by s0me1newithhand7s** [comment]
> I still don't get why would you use ubuntu/debian over alpine for the whole Dockerfile — the resulting image would be more heavy

i'm not rewriting whole `Dockerfile` - it is just a *refactor*

**Comment by KiGamji** [comment]
the question still remains

**Comment by s0me1newithhand7s** [comment]
> the question still remains

because it wasn't written originally this way, so i consider not to

**Comment by KiGamji** [comment]
I did some tests — with alpine it took me 315 seconds to build and takes 285 MB of storage, while with ubuntu:devel it now takes 296 seconds and takes 404 MB.

Also, the container now crashes:
3x-ui  | Server ready
3x-ui  | /app/DockerEntrypoint.sh: 7: exec: /app/x-ui: not found

**Comment by s0me1newithhand7s** [comment]
> I did some tests — with alpine it took me 315 seconds to build and takes 285 MB of storage, while with ubuntu:devel it now takes 296 seconds and takes 404 MB.
> 
> Also, the container now crashes: 3x-ui | Server ready 3x-ui | /app/DockerEntrypoint.sh: 7: exec: /app/x-ui: not found

hm strange, mine haven't this issue

**Comment by s0me1newithhand7s** [comment]
but thanks for reporting, i'll try to fix it

**Comment by s0me1newithhand7s** [comment]
sorry for not updating you; i'm trying to rewrite `Dockerfile` and test it locally

**Comment by fuwaneko** [comment]
> > I still don't get why would you use ubuntu/debian over alpine for the whole Dockerfile — the resulting image would be more heavy
> 
> i'm not rewriting whole `Dockerfile` - it is just a _refactor_

You have no idea what you're doing, haven't you? I see absolutely no point in the changes proposed in this PR. Can you please provide any good rationale for these “refactors”?

**Comment by s0me1newithhand7s** [comment]
> You have no idea what you're doing, haven't you? I see absolutely no point in the changes proposed in this PR. Can you please provide any good rationale for these “refactors”?

i'm trying to abandon process of using unsupported `alpine linux`. unsupported by who? by x-ui and 3x-ui.
why? even at docker it's means, as my friends and me found. :D

**Comment by KiGamji** [comment]
unsupported? huh???

**Pull request closed without merging**
