### PR TITLE
update

### PR DESCRIPTION
**Pull request by MHSanaei**

### CODE REVIEW

**Comment by pchreza** [comment]
hi bro tnx for your god x-ui 
How can several outbands be connected to x-ui as proxy servers?

**Comment by Mostafa-kaveh** [comment]
Hello
Thank you very much for your hard work
In the new update, I cannot add a user with a new email

**Comment by allahyar** [comment]
Hello
SSL that is created, the panel does not accept, what is the problem?
image

**Comment by Moein-1986** [comment]
Hello
Tls is not working in new update
Please fix that

**Comment by pchreza** [comment]
> Hello SSL that is created, the panel does not accept, what is the problem? image
In this error, it says that there is no such file in this path, you should check your path or move your certificate files.

**Pull request merged**
