### PR TITLE
enable traffic + block IR domain

### PR DESCRIPTION
**Pull request by MHSanaei**

### CODE REVIEW

**Comment by Rahattt** [comment]
Add please TURKMENISTAN IP BLOCK

**Comment by MHSanaei** [comment]
@Rahattt change geoip:ir to geoip:tn

**Comment by Rahattt** [comment]
> @Rahattt change geoip:ir to geoip:tn

geoip:tn or geoip:tm?

**Comment by Rahattt** [comment]
and is it possible to ban a domain such as "example.com"?

**Comment by MHSanaei** [comment]
i don't know really i just Google it , it was tn
and for domain yes you can block any domain you want

**Pull request merged**
