### PR TITLE
Fixed Russian translation

### PR DESCRIPTION
**Pull request by farag2**
Fixed Russian translation 🐱

### CODE REVIEW

**Comment by farag2** [comment]
How to translate this word `running`? I couldn't find it in `https://github.com/MHSanaei/3x-ui/blob/main/web/translation/translate.ru_RU.toml`

изображение

**Comment by Handset** [comment]
Hi, the word translates as "Запущен", but it's not worth translating, I think everyone will understand it in English

**Comment by farag2** [comment]
Hm... For me it looks ugly.

**Comment by Handset** [comment]
I'm sorry, I misunderstood the question) Deleting a comment

**Pull request merged**
